---
driver:
  name: vagrant

provisioner:
  name: chef_zero

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

platforms:
- name: ubuntu-15.04

suites:
- name: default
  run_list:
    - recipe[line]
    - recipe[line_test]
  attributes: {}
