---
driver:
  name: vagrant

provisioner:
  name: chef_zero

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

verifier: inspec

platforms:
- name: ubuntu-15.04

suites:
- name: delete_from_list
  run_list:
    - recipe[test::delete_from_list]
- name: add_to_list
  run_list:
    - recipe[test::add_to_list]
- name: append_if_no_line
  run_list:
    - recipe[test::append_if_no_line]
- name: delete_lines
  run_list:
    - recipe[test::delete_lines]
- name: replace_or_add
  run_list:
    - recipe[test::resource_status]
    - recipe[test::replace_or_add_add_a_line_matching_pattern]
    - recipe[test::replace_or_add_change_line_eof]
    - recipe[test::replace_or_add_duplicate]
    - recipe[test::replace_or_add_missing_file]
    - recipe[test::replace_or_add_replace_only]
    - recipe[test::replace_or_add_unmatched]
    - recipe[test::replace_or_add]
