name             'line'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Provides line editing resources for use by recipes'

version          '4.6.0'

source_url       'https://github.com/sous-chefs/line'
issues_url       'https://github.com/sous-chefs/line/issues'
chef_version     '>= 15.3'

supports 'debian'
supports 'ubuntu'
supports 'centos'
supports 'redhat'
supports 'scientific'
supports 'oracle'
supports 'amazon'
supports 'windows'
